trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

steps:
- checkout: self

- task: UsePythonVersion@0
  displayName: 'Use Python $(pythonVersion)'
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd backend
    python manage.py migrate --noinput
    python manage.py collectstatic --noinput
  displayName: 'Prepare database and static files'

- script: |
    cd backend
    python manage.py runserver 0.0.0.0:8000 &
    SERVER_PID=$!
    echo "Waiting for server to start..."
    sleep 6
    echo "Health check"
    curl -f http://127.0.0.1:8000/api/health/ || (echo "Health check failed" && kill $SERVER_PID && exit 1)
    echo "Shutting down server"
    kill $SERVER_PID
  displayName: 'Run app and health check' 