# Generated by Django 5.2.4 on 2025-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
