# Generated by Django 5.2.4 on 2025-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_fileupload_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='jobrun_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='job_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
