# Generated by Django 5.2.4 on 2025-08-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_monthlyauditreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='product',
            field=models.CharField(choices=[('FACETS', 'Facets'), ('QNXT', 'QNXT'), ('CAE', 'CAE'), ('TMS', 'TMS'), ('EDM', 'EDM'), ('CLSP', 'CLSP')], default='FACETS', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.CharField(choices=[('FACETS', 'Facets'), ('QNXT', 'QNXT'), ('CAE', 'CAE'), ('TMS', 'TMS'), ('EDM', 'EDM'), ('CLSP', 'CLSP')], default='FACETS', max_length=50),
        ),
        migrations.AddField(
            model_name='sladata',
            name='product',
            field=models.CharField(choices=[('FACETS', 'Facets'), ('QNXT', 'QNXT'), ('CAE', 'CAE'), ('TMS', 'TMS'), ('EDM', 'EDM'), ('CLSP', 'CLSP')], default='FACETS', max_length=50),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['product'], name='dashboard_a_product_7fe679_idx'),
        ),
        migrations.AddIndex(
            model_name='sladata',
            index=models.Index(fields=['product'], name='dashboard_a_product_d9770d_idx'),
        ),
    ]
