# Generated by Django 5.2.4 on 2025-08-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_add_account_request_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sladata',
            options={'ordering': ['-date', 'customer', 'job_name'], 'verbose_name': 'SLA Analysis Result', 'verbose_name_plural': 'SLA Analysis Results'},
        ),
        migrations.AlterUniqueTogether(
            name='sladata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sladata',
            name='actual_completion_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sladata',
            name='analyzed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sladata',
            name='batch_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_analysis', to='dashboard_app.batchjob'),
        ),
        migrations.AddField(
            model_name='sladata',
            name='completed_next_day',
            field=models.BooleanField(default=False, help_text='Job completed after midnight'),
        ),
        migrations.AddField(
            model_name='sladata',
            name='days_late',
            field=models.IntegerField(default=0, help_text='Number of days beyond target date'),
        ),
        migrations.AddField(
            model_name='sladata',
            name='sla_target_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='actual_runtime_minutes',
            field=models.FloatField(help_text='Actual completion time in minutes from start of day'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='product',
            field=models.CharField(choices=[('FACETS', 'Facets'), ('QNXT', 'QNXT'), ('CAE', 'CAE'), ('TMS', 'TMS'), ('EDM', 'EDM'), ('CLSP', 'CLSP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='sla_status',
            field=models.CharField(choices=[('MET', 'SLA Met'), ('MISSED', 'SLA Missed'), ('AT_RISK', 'At Risk'), ('NO_SLA', 'No SLA Defined')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='sla_target_minutes',
            field=models.FloatField(help_text='Target time in minutes from midnight'),
        ),
        migrations.AlterUniqueTogether(
            name='sladata',
            unique_together={('customer', 'product', 'job_name', 'date', 'batch_job')},
        ),
        migrations.CreateModel(
            name='SLADefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('FACETS', 'Facets'), ('QNXT', 'QNXT'), ('CAE', 'CAE'), ('TMS', 'TMS'), ('EDM', 'EDM'), ('CLSP', 'CLSP')], max_length=50)),
                ('job_name', models.CharField(max_length=200)),
                ('sla_target_time', models.TimeField(help_text='Expected completion time (e.g., 23:50 for 11:50 PM)')),
                ('description', models.TextField(blank=True, help_text='Description of this SLA')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_definitions', to='dashboard_app.customer')),
            ],
            options={
                'verbose_name': 'SLA Definition',
                'verbose_name_plural': 'SLA Definitions',
                'ordering': ['customer', 'product', 'job_name'],
            },
        ),
        migrations.AddField(
            model_name='sladata',
            name='sla_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_results', to='dashboard_app.sladefinition'),
        ),
        migrations.AddIndex(
            model_name='sladata',
            index=models.Index(fields=['date'], name='dashboard_a_date_135011_idx'),
        ),
        migrations.AddIndex(
            model_name='sladefinition',
            index=models.Index(fields=['customer', 'product'], name='dashboard_a_custome_d9c203_idx'),
        ),
        migrations.AddIndex(
            model_name='sladefinition',
            index=models.Index(fields=['job_name'], name='dashboard_a_job_nam_a3ba2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sladefinition',
            unique_together={('customer', 'product', 'job_name')},
        ),
    ]
