# Generated by Django 5.2.4 on 2025-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_sla_transformation_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='exit_code',
            field=models.IntegerField(blank=True, help_text='Exit code from batch job execution', null=True),
        ),
    ]
