# Generated by Django 5.2.4 on 2025-08-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_add_exit_code_to_batch_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyAuditReport',
        ),
    ]
