# Generated by Django 5.2.4 on 2025-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_remove_monthly_audit_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchschedule',
            options={'ordering': ['job_name', 'priority']},
        ),
        migrations.RemoveIndex(
            model_name='batchschedule',
            name='dashboard_a_next_ru_a7368b_idx',
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='agent_or_agent_list',
            field=models.CharField(blank=True, help_text='RUNS ON AGENT OR AGENT LIST? from Excel', max_length=200),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='calendar',
            field=models.CharField(blank=True, help_text='CALENDAR from Excel', max_length=200),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='calendar_offset',
            field=models.CharField(blank=True, help_text='CALENDAR OFFSET from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='category',
            field=models.CharField(choices=[('JOB', 'Job'), ('FOLDER', 'Folder'), ('CONDITION', 'Condition'), ('RESOURCE', 'Resource')], default='JOB', help_text='CATEGORY from Excel', max_length=20),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='class_name',
            field=models.CharField(blank=True, help_text='CLASS from Excel', max_length=200),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='enabled_status',
            field=models.CharField(blank=True, help_text='ENABLED OR DISABLED? from Excel', max_length=20),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='job_id',
            field=models.CharField(blank=True, help_text='ID from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='last_modified_on',
            field=models.DateTimeField(blank=True, help_text='LAST MODIFIED ON from Excel', null=True),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='owner',
            field=models.CharField(blank=True, help_text='OWNER from Excel', max_length=200),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='parent_group',
            field=models.CharField(blank=True, help_text='PARENT GROUP from Excel', max_length=500),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='start_time',
            field=models.CharField(blank=True, help_text='Start time from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='time_zone',
            field=models.CharField(blank=True, default='DEFAULT (E.S.T.)', help_text='Time Zone from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='until_time',
            field=models.CharField(blank=True, help_text='Until time from Excel', max_length=100),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='dependencies',
            field=models.TextField(blank=True, help_text='DEP UPON JOB/VARIABLE/FILE from Excel'),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='job_name',
            field=models.CharField(help_text='JOBNAME from Excel', max_length=200),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='last_run_time',
            field=models.DateTimeField(blank=True, help_text='Legacy field', null=True),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='next_run_time',
            field=models.DateTimeField(blank=True, help_text='Legacy field or calculated', null=True),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='priority',
            field=models.IntegerField(default=1, help_text='Legacy field'),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='schedule_name',
            field=models.CharField(blank=True, help_text='Legacy field or derived from job_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='schedule_pattern',
            field=models.CharField(blank=True, help_text='Legacy field or derived from calendar', max_length=100),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('MAINTENANCE', 'Under Maintenance'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='batchschedule',
            index=models.Index(fields=['job_name'], name='dashboard_a_job_nam_53414e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchschedule',
            index=models.Index(fields=['category'], name='dashboard_a_categor_a9d30b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchschedule',
            index=models.Index(fields=['enabled_status'], name='dashboard_a_enabled_27c6d6_idx'),
        ),
    ]
