# Generated by Django 5.2.4 on 2025-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_predictionmodel_predictionresult_predictionalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchschedule',
            name='agent_agent_list',
            field=models.CharField(blank=True, help_text='Agent / Agent List from Excel', max_length=200),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='allow_operator_rerun',
            field=models.CharField(blank=True, help_text='Allow operator rerun? from Excel', max_length=10),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='allow_unscheduled',
            field=models.CharField(blank=True, help_text='Allow unscheduled? from Excel', max_length=10),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='amount_required',
            field=models.IntegerField(blank=True, help_text='AMOUNT REQUIRED from Excel', null=True),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='command',
            field=models.TextField(blank=True, help_text='COMMAND from Excel'),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='disable_carryover',
            field=models.CharField(blank=True, help_text='Disable Carryover? from Excel', max_length=10),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='exclude_completed_abnormally',
            field=models.CharField(blank=True, help_text='Exclude Completed Abnormally? from Excel', max_length=50),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='exit_code_range',
            field=models.CharField(blank=True, help_text='Exit code range: from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='for_tracking_use',
            field=models.CharField(blank=True, default='Exit code', help_text='FOR TRACKING, USE: from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='history_retention_days',
            field=models.IntegerField(blank=True, help_text='HISTORY RETENTION (DAYS) from Excel', null=True),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='if_job_currently_running',
            field=models.CharField(blank=True, help_text='If job is currently running: from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='if_not_enough_time_b4_outage',
            field=models.CharField(blank=True, help_text='If not enough time b4 outage from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='max_number_of_runs',
            field=models.IntegerField(blank=True, help_text='MAX NUMBER OF RUNS from Excel', null=True),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes from Excel'),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='parameters',
            field=models.TextField(blank=True, help_text='Parameters from Excel'),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='repeats',
            field=models.CharField(blank=True, default='DO NOT REPEAT', help_text='REPEATS from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='require_operator_release',
            field=models.CharField(blank=True, help_text='Require operator release? from Excel', max_length=10),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='required_virtual_resource',
            field=models.CharField(blank=True, help_text='REQUIRED VIRTUAL RESOURCE from Excel', max_length=200),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='run_book',
            field=models.TextField(blank=True, help_text='run book from Excel'),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='run_new_rerun_same',
            field=models.CharField(blank=True, help_text='RUN NEW/RERUN SAME OCCURRENCE? from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='runtime_user',
            field=models.CharField(blank=True, help_text='RUNTIME USER from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='save_output_option',
            field=models.CharField(blank=True, help_text='Save Output Option from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='scan_output_normal',
            field=models.CharField(blank=True, help_text='SCAN OUTPUT: NORMAL from Excel', max_length=100),
        ),
    ]
