# Generated by Django 5.2.4 on 2025-08-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_batchschedule_agent_agent_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchschedule',
            name='job_type',
            field=models.CharField(choices=[('INDIVIDUAL_JOB', 'Individual Job'), ('JOB_GROUP', 'Job Group'), ('FOLDER_GROUP', 'Folder Group'), ('DEPENDENCY', 'Dependency'), ('CONDITION_CHECK', 'Condition Check'), ('RESOURCE_POOL', 'Resource Pool')], default='INDIVIDUAL_JOB', help_text='Derived job type based on analysis', max_length=30),
        ),
        migrations.AlterField(
            model_name='batchschedule',
            name='category',
            field=models.CharField(choices=[('JOB', 'Job'), ('FOLDER', 'Folder'), ('CONDITION', 'Condition'), ('RESOURCE', 'Resource'), ('VARIABLE', 'Variable'), ('CONNECTION', 'Connection'), ('CALENDAR', 'Calendar'), ('AGENT', 'Agent'), ('GROUP', 'Group')], default='JOB', help_text='CATEGORY from Excel', max_length=20),
        ),
    ]
