# Generated by Django 5.2.4 on 2025-08-12 02:24

from django.db import migrations


def update_job_to_type(apps, schema_editor):
    """Update all BatchSchedule records from category='JOB' to category='TYPE'"""
    BatchSchedule = apps.get_model('dashboard_app', 'BatchSchedule')
    
    # Update all records with category='JOB' to category='TYPE'
    updated_count = BatchSchedule.objects.filter(category='JOB').update(category='TYPE')
    print(f"Updated {updated_count} BatchSchedule records from category='JOB' to category='TYPE'")


def reverse_type_to_job(apps, schema_editor):
    """Reverse migration: Update all BatchSchedule records from category='TYPE' to category='JOB'"""
    BatchSchedule = apps.get_model('dashboard_app', 'BatchSchedule')
    
    # Reverse: update all records with category='TYPE' to category='JOB'
    updated_count = BatchSchedule.objects.filter(category='TYPE').update(category='JOB')
    print(f"Reversed {updated_count} BatchSchedule records from category='TYPE' to category='JOB'")


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0014_batchschedule_job_type_alter_batchschedule_category'),
    ]

    operations = [
        migrations.RunPython(update_job_to_type, reverse_type_to_job),
    ]
