# Generated by Django 5.2.4 on 2025-08-12 02:37

from django.db import migrations


def update_type_to_tid(apps, schema_editor):
    BatchSchedule = apps.get_model('dashboard_app', 'BatchSchedule')
    updated_count = BatchSchedule.objects.filter(category='TYPE').update(category='TID')
    print(f"Updated {updated_count} BatchSchedule records from category='TYPE' to category='TID'")


def reverse_tid_to_type(apps, schema_editor):
    BatchSchedule = apps.get_model('dashboard_app', 'BatchSchedule')
    updated_count = BatchSchedule.objects.filter(category='TID').update(category='TYPE')
    print(f"Reversed {updated_count} BatchSchedule records from category='TID' to category='TYPE'")


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0015_auto_20250812_0754'),
    ]

    operations = [
        migrations.RunPython(update_type_to_tid, reverse_tid_to_type),
    ]
