# Generated by Django 5.2.4 on 2025-08-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0016_auto_20250812_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchschedule',
            name='category',
            field=models.CharField(choices=[('TID', 'TID'), ('FOLDER', 'Folder'), ('CONDITION', 'Condition'), ('RESOURCE', 'Resource'), ('VARIABLE', 'Variable'), ('CONNECTION', 'Connection'), ('CALENDAR', 'Calendar'), ('AGENT', 'Agent'), ('GROUP', 'Group')], default='TID', help_text='CATEGORY from Excel', max_length=20),
        ),
    ]
